target_col: Legendary
test_size: 0.2
random_state: 42
numeric_cols: ["HP","Attack","Defense","Sp. Atk","Sp. Def","Speed","Total"]
cat_cols: ["Type 1","Type 2"]
rf_params:
  n_estimators: 400
  max_depth: null
  class_weight: balanced

